'use client';

import { useState } from 'react';
import Link from 'next/link';
import { notFound, useParams } from 'next/navigation';
import { ArrowLeft, ArrowRight, FileLock2, MapPin, ShieldCheck } from 'lucide-react';
import { Navbar } from '../../../components/public-platform/Navbar';
import { InvestorRegistrationModal } from '../../../components/public-platform/InvestorRegistrationModal';
import { ELURIA_OPPORTUNITIES } from '../../../data/eluria/opportunities';

export default function OpportunityDetailPage() {
  const params = useParams<{ id: string }>();
  const opportunity = ELURIA_OPPORTUNITIES.find((item) => item.slug === params.id || item.id === params.id);
  const [isRegistrationOpen, setIsRegistrationOpen] = useState(false);
  const [accessRequested, setAccessRequested] = useState(false);
  if (!opportunity) notFound();

  return <div className="min-h-screen bg-[#0B192C] text-slate-100"><Navbar /><main className="mx-auto max-w-7xl px-6 py-12 lg:px-8">
    <Link href="/invest" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft className="size-4" />All opportunities</Link>
    <div className="mt-7 grid gap-10 lg:grid-cols-[1.2fr_0.8fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-400">{opportunity.category}</p><h1 className="mt-3 text-4xl font-bold text-white sm:text-5xl">{opportunity.title}</h1><p className="mt-4 flex items-center gap-2 text-slate-300"><MapPin className="size-4 text-amber-400" />{opportunity.location}</p><p className="mt-7 text-lg leading-relaxed text-slate-300">{opportunity.overview}</p></div><div className="relative min-h-64 bg-slate-800"><img src={opportunity.featuredImage} alt="" className="absolute inset-0 h-full w-full object-cover" /><span className="absolute left-4 top-4 bg-amber-400 px-3 py-1.5 text-xs font-bold text-slate-950">{opportunity.status}</span></div></div>
    <section className="mt-14 grid gap-10 border-t border-slate-800 py-10 lg:grid-cols-[1fr_0.75fr]"><div><h2 className="text-2xl font-bold text-white">Market & industry</h2><p className="mt-4 max-w-3xl text-sm leading-relaxed text-slate-300">{opportunity.marketIndustry}</p><h2 className="mt-10 text-2xl font-bold text-white">Project highlights</h2><ul className="mt-5 space-y-3">{opportunity.publicHighlights.map((highlight) => <li key={highlight} className="flex gap-3 text-sm text-slate-300"><ShieldCheck className="size-4 shrink-0 text-amber-400" />{highlight}</li>)}</ul></div><aside className="border border-slate-800 bg-slate-900/60 p-6"><p className="text-xs font-semibold uppercase tracking-wider text-amber-400">Investment requirements</p><dl className="mt-5 space-y-4 text-sm"><div className="flex justify-between gap-5 border-b border-slate-800 pb-3"><dt className="text-slate-400">Minimum ticket</dt><dd className="font-semibold text-white">{opportunity.minTicket}</dd></div><div className="flex justify-between gap-5 border-b border-slate-800 pb-3"><dt className="text-slate-400">Target raise</dt><dd className="font-semibold text-white">{opportunity.targetRaise}</dd></div><div className="flex justify-between gap-5 border-b border-slate-800 pb-3"><dt className="text-slate-400">Investment range</dt><dd className="font-semibold text-white">{opportunity.investmentRange}</dd></div><div className="flex justify-between gap-5"><dt className="text-slate-400">Expected return</dt><dd className="font-semibold text-white">{opportunity.expectedReturns}</dd></div></dl></aside></section>
    {opportunity.isConfidential && <section className="mt-4 border border-amber-500/40 bg-slate-900"><div className="flex flex-col gap-5 p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"><div className="flex gap-4"><div className="grid size-11 shrink-0 place-items-center border border-amber-500/40 bg-amber-500/10 text-amber-300"><FileLock2 className="size-5" /></div><div><p className="text-xs font-semibold uppercase tracking-wider text-amber-300">Confidential Virtual Data Room</p><h2 className="mt-2 text-xl font-bold text-white">Detailed diligence materials are protected</h2><p className="mt-2 max-w-xl text-sm leading-relaxed text-slate-400">Financial models, the full Information Memorandum, and engineering blueprints are available after investor registration and review.</p><p className="mt-3 text-xs text-slate-500">{opportunity.protectedDocCount} protected documents</p>{accessRequested && <p role="status" className="mt-3 text-sm text-emerald-300">Your investor access request has been received for review.</p>}</div></div>{!accessRequested && <button type="button" onClick={() => setIsRegistrationOpen(true)} className="inline-flex h-11 shrink-0 items-center justify-center gap-2 bg-amber-500 px-5 text-sm font-bold text-slate-950">Request Investor Access <ArrowRight className="size-4" /></button>}</div></section>}
  </main>{isRegistrationOpen && <InvestorRegistrationModal onClose={() => setIsRegistrationOpen(false)} onAccessRequested={() => setAccessRequested(true)} />}</div>;
}
