import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
import { Navbar } from '../../components/public-platform/Navbar';
import { ELURIA_SERVICES } from '../../data/eluria/services';

const values = [
  { title: 'Technical Excellence', description: 'Apply sound engineering methods, measurable standards, and disciplined delivery.' },
  { title: 'Environmental Stewardship', description: 'Consider environmental and social impacts throughout project planning and operations.' },
  { title: 'Governance & Integrity', description: 'Build transparent processes, accountable partnerships, and responsible data practices.' },
];

export default function AboutPage() {
  return <div className="min-h-screen bg-[#0B192C] text-slate-100"><Navbar /><main className="mx-auto max-w-7xl px-6 py-16 lg:px-8">
    <header className="max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-400">About Eluria Group</p><h1 className="mt-3 text-4xl font-bold text-white sm:text-5xl">Engineering sustainable industrial growth across Africa</h1><p className="mt-6 text-lg leading-relaxed text-slate-300">Eluria Group is an integrated engineering, environmental compliance, and infrastructure development consortium. We identify, structure, and de-risk high-conviction industrial opportunities, connecting technical execution with responsible investment.</p></header>
    <section className="mt-14 grid gap-6 md:grid-cols-2"><article className="border border-slate-800 bg-slate-900/60 p-7"><p className="text-xs font-semibold uppercase tracking-wider text-amber-400">Our mission</p><h2 className="mt-3 text-xl font-bold text-white">Make essential infrastructure work better</h2><p className="mt-3 text-sm leading-relaxed text-slate-300">Deploy world-class technical solutions that drive resource efficiency and industrial capacity.</p></article><article className="border border-slate-800 bg-slate-900/60 p-7"><p className="text-xs font-semibold uppercase tracking-wider text-amber-400">Our vision</p><h2 className="mt-3 text-xl font-bold text-white">A trusted regional delivery partner</h2><p className="mt-3 text-sm leading-relaxed text-slate-300">To be West Africa&apos;s leading infrastructure and environmental services partner.</p></article></section>
    <section className="mt-14"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-wider text-amber-400">How we work</p><h2 className="mt-2 text-2xl font-bold text-white">Core values</h2></div></div><div className="mt-5 grid gap-4 md:grid-cols-3">{values.map((value) => <article key={value.title} className="border border-slate-800 bg-slate-900/60 p-5"><CheckCircle2 className="size-5 text-amber-400" /><h3 className="mt-4 font-bold text-white">{value.title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-400">{value.description}</p></article>)}</div></section>
    <section className="mt-14 border-y border-slate-800 py-9"><p className="text-xs font-semibold uppercase tracking-wider text-amber-400">Areas of expertise</p><div className="mt-5 flex flex-wrap gap-2">{ELURIA_SERVICES.map((service) => <Link key={service.slug} href="/services" className="border border-slate-700 px-3 py-2 text-xs text-slate-300 hover:border-amber-500/60 hover:text-white">{service.title}</Link>)}</div></section>
    <section className="mt-16 grid gap-8 border-t border-slate-800 pt-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div className="relative mx-auto aspect-4/5 w-full max-w-sm overflow-hidden bg-slate-800"><Image src="/team/daniel-appiah.jpg" alt="Daniel Appiah, Founder and Chief Executive Officer of Eluria Group" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 400px" /></div><div><p className="text-xs font-semibold uppercase tracking-wider text-amber-400">Leadership</p><h2 className="mt-3 text-3xl font-bold text-white">Daniel Appiah</h2><p className="mt-2 text-sm font-semibold text-slate-300">Founder & Chief Executive Officer / Engineering, Environmental & HSE Compliance Leader</p><p className="mt-5 text-sm leading-relaxed text-slate-400">Daniel leads Eluria Group with a focus on industrial transformation, sustainable infrastructure, and disciplined capital deployment across strategic African markets. His work brings together engineering delivery, environmental responsibility, and operational HSE compliance.</p><h3 className="mt-7 text-xs font-semibold uppercase tracking-wider text-slate-300">Professional credentials & expertise</h3><ul className="mt-3 space-y-2 text-sm text-slate-400"><li>Engineering leadership</li><li>Environmental compliance leadership</li><li>Health, safety, and environmental (HSE) compliance leadership</li></ul><Link href="/leadership" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-amber-400">Leadership profile <ArrowRight className="size-4" /></Link></div></section>
  </main></div>;
}
